---

- name: Install Plone and all its dependencies
  hosts: all
  user: vagrant
  sudo: yes

  roles:
   - apt-update
   - apt-upgrade
   - ubuntu_packages
   - download_plone_installer
   - run_installer
